name: doc

on:
  push:
    branches:
      - master

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.3.5"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: install dependencies
      run: |
        luarocks install ldoc

    - name: build documentation
      run: |
        ldoc .

    - name: publish documentation
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: doc
